# Generated by Django 5.1.6 on 2026-02-05 14:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_messagefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=api.models.upload_to_path),
        ),
    ]
