# Generated by Django 5.2.11 on 2026-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefeedback',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messagefeedback',
            name='query',
            field=models.TextField(blank=True, default=''),
        ),
    ]
